# Generated by Django 4.2.11 on 2026-05-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='ARS', max_length=3)),
                ('members', models.JSONField(default=list)),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_by', models.CharField(max_length=200)),
                ('paid_to', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('expense', 'Gasto'), ('settlement', 'Liquidación')], default='expense', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_currency', models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], max_length=3)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.group')),
            ],
        ),
    ]
