# Generated by Django 6.0.1 on 2026-03-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='currency',
            field=models.CharField(default=None),
        ),
    ]
