# Generated by Django 6.0.1 on 2026-03-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_group_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.JSONField(default=list),
        ),
    ]
