# Generated by Django 6.0.1 on 2026-03-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
