# Generated by Django 6.0.4 on 2026-05-04 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_alter_expense_id_alter_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='member_joined_dates',
            field=models.JSONField(default=dict),
        ),
    ]
