# Generated by Django 6.0.4 on 2026-05-07 19:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0008_expense_created_group_member_joined_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='original_currency',
            field=models.CharField(choices=[('ARS', 'Pesos (ARS)'), ('USD', 'Dólares (USD)'), ('EUR', 'Euros (EUR)')], default='ARS', max_length=3),
        ),
    ]
